### ISSUE TITLE
Improve sound API

### ISSUE THREAD

**Issue by ryanisaacg** [ryanisaacg/quicksilver#219]
Currently there's no way in quicksilver to do things like left / right balancing, largely because I personally neglect sound in my own projects. The sound API is in sore need of some touchups.

- [ ] Load sounds from a binary chunk
- [ ] Play a sound
- [ ] Loop a sound
- [ ] Left / right balancing
- [ ] Hold a handle to a playing sound
    - [ ] Pause/Resume the sound
    - [ ] Stop the sound
    - [ ] Query if that sound is playing

**Comment by ryanisaacg** [comment]
It seems left / right balance, pitch effects, and fade out aren't possible within Rodio, and guaranteeing music is streaming doesn't seem possible or easy on web. As a result, this has to be pared back a bit.

**Comment by ryanisaacg** [comment]
For clarity's sake, I've marked this as blocked until cpal / rodio support web.

**Comment by paulirotta** [comment]
Doesn't `cpal` now support web? This example appeared 2 months ago, have not tested.

https://github.com/RustAudio/cpal/tree/master/examples/wasm-beep

**Comment by ryanisaacg** [comment]
Yup, but with a significant latency. Last I saw their latency was around 100ms, which is mostly not acceptable for a game usecase.

**Comment by lenscas** [comment]
Maybe its a good idea to start writing an API for it anyway? I also don't mind to write some temporary JS bindings to something like [howler.js](https://github.com/goldfire/howler.js/), nor do I mind to maintain them until they can be replaced by a pure rust library.

I think using howler.js would solve the latency issue that cpal is currently having, as it seems that the latency is caused by the WASM <-> webaudio api (though admittedly, I didn't look into it too much).

I actually think I already have some rust bindings to howler.js somewhere. They are made using std-web and I'm not sure about their quality but they at least should be a start.

**Comment by ryanisaacg** [comment]
My plan currently is to create a standalone crate that implements something like the WebAudio API on top of rodio (and obviously also the WebAudio API) and then wrap that into a simple and easy-to-use version for Quicksilver.

Regardless, this issue is about upgrading the old sound API which isn't really the path that needs to be taken anymore. We can just build something satisfactory from the beginning.

**Comment by jgarvin** [comment]
@lenscas When I was evaluating different 2D game crates, I came across [gate](https://github.com/SergiusIW/gate/blob/0916203899c3aa89d049bf4af38db3961924ad9a/example/README.md), which already uses `howler.js` for audio. Figured I'd mention in case a working example would make things easier.
