### ISSUE TITLE
gfx-rs backend support

### ISSUE THREAD

**Issue by ryanisaacg** [ryanisaacg/quicksilver#236]
What with [Apple's deprecation of OpenGL](https://developer.apple.com/macos/whats-new/), Metal will be the only supported way to accelerate graphics on Mac. Additionally, OpenGL is definitely a second-class citizen on Windows. 

The options to go forward are either maintain backends for each graphics API (OpenGL, WebGL, and now Metal) or try to use a Rust graphics library which will support all of them.

Currently it doesn't seem gfx supports WebGL on wasm32, but there's already a split between desktop and web backends. 

However, it doesn't make sense to switch to a crate preparing to undergo major breaking changes, so it seems best to wait for [the HAL update](https://github.com/gfx-rs/gfx/milestone/9)

**Comment by memoryruins** [comment]
Agreed, waiting for gfx-hal's is the most sensible choice. Since OpenGL, even though deprecated, will continue to run on macOS for some more time, a metal backend might not need to be added anytime soon. It can be gained through gfx-hal when its ready. Today kvark posted ["First screenshot of Dota2 running on gfx-portabilty with Metal backend"](https://www.reddit.com/r/rust/comments/8pmniu/first_screenshot_of_dota2_running_on/) on reddit. Progress ^^

**Comment by Palladinium** [comment]
I'm not very knowledgeable on low-level graphics APIs, but with I'd be keen to try my hand at spearheading this.

A thought: should the backend be built straight on top of `gfx-rs`, or through `rendy` (as ggez and Amethyst did)?
From what I can tell, `gfx-rs` supports OpenGL and WebGL while `rendy` doesn't (yet).

**Comment by ryanisaacg** [comment]
@Palladinium I think the best option for a graphics API that uses gfx-rs is wgpu, because it will (hypothetically in the future) have the best web support.

**Comment by ryanisaacg** [comment]
With the new alpha, the graphics API is handled by [`golem`](https://github.com/ryanisaacg/golem). Currently there's no pressing need to move away from GL, and golem can handle this without rewrites Quicksilver-side, so this can be closed.
