### ISSUE TITLE
Consider removing Line::new_sized()

### ISSUE THREAD

**Issue by Xoronic** [ryanisaacg/quicksilver#308]
### 1: It is not very clear that a 'sized' line is created along the x-axis.

```rust
Line::new(Vector::ZERO, Vector::X * 5);
```

or

```rust
Line::new((0, 0), (5, 0));
```

Is way clearer than 

```rust
Line::new_sized(5);
```

### 2: It is never used in quicksilver yet
The only place where the function is used is in tests!

### 3: When in doubt, leave it out
It can always be added back later. The project is not tied to being backwards compatible *yet*

**Comment by Byter09** [comment]
The only reason I did it like that is because I copied the already existing methods used in `Rectangle` or `Circle`. I really had no intention of even adding that method in the first place, but thought maybe its useful to someone and that there must be a reason for the other objects to have such a method.

**Comment by ryanisaacg** [comment]
I wouldn't object to it being removed, I'll get around to it at some point if no one else does.
