### ISSUE TITLE
window::draw functions confusion

### ISSUE THREAD

**Issue by Xoronic** [ryanisaacg/quicksilver#315]
I just cannot figure out why it is called draw_ex and why it is different from `draw` and `draw_color`..

From looking at the implementation of the function, I can tell that it has an extra z parameter? *But what does `ex` mean?*

### 1: Change the documentation for `draw`, `draw_color`, `draw_ex` and `draw_params` functions
Right now, all of the draw functions have the same documentation: 

```
    /// Draw a single object to the screen
    ///
    /// It will not appear until Window::flush is called
```

If multiple functions have the exact same documentation, the documentation loses its worth.

### 2: Rename `draw_ex` to something that is clear
I have no idea what `ex` stands for, even after looking at the implementation. I get that function names should be not too long to type, but `draw_ex` is *too* short.

### 3: Changing the `draw` and `draw_color` function
Leave transformation for specialized draw-functions, and drop it for the simplest one. All shapes already have a position, don't they? At least `Rectangle`, `Circle` and `Line` do have positions.

**Comment by Byter09** [comment]
This is something I wondered since it was implemented. Though, I liked the change and simply did not complain :P

There should be default methods, and then per-parameter advanced ones.

For example:

`draw`, defaults to: `Transform::IDENTITY`, `Color::WHITE` and z = 0.

Then there could be a draw_z, which has the same parameters as draw but additionally one can provide a z value. Same with transformations and colours. But this is all just QoL stuff, that's not really important, if the most complex forms of `draw` are available. So yeah I agree with you but I'd say this is not something of a timely matter.

**Comment by Xoronic** [comment]
I like your suggestion of a `draw_z`!

However, I think it is important to think about the API now, and not later. A good API is essential for a library to gain success. Also, it is hard to change it later.

**Comment by Byter09** [comment]
Okay, now lets see:
Let's temporarily forget which methods are already available and see in what different ways we can draw, given the following parameters
- Drawable (always present)
- Colour
- Z-axis change
- Transform

The last three are already nicely configurable thanks to the `DrawAttributes` struct.
If we sorted the methods from simple to complex and do not leave any variant open, we'd end up with this list:
```rust
// most basic, using default values of `DrawAttributes`
pub fn draw_simple(&mut self, item: &impl Drawable);

// these three use the same values as `draw_simple`, except for one value changed
pub fn draw_with_color(&mut self, item: &impl Drawable, color: Color);
pub fn draw_with_transform(&mut self, item: &impl Drawable, trans: Transform);
pub fn draw_with_z(&mut self, item: &impl Drawable, z: impl Scalar);

// not sure about these...
pub fn draw_with_color_transformed(&mut self, item: &impl Drawable, color: Color, trans: Transform);
pub fn draw_with_color_z(&mut self, item: &impl Drawable, color: Color, z: impl Scalar);
pub fn draw_with_transform_z(&mut self, item: &impl Drawable, trans: Transform, z: impl Scalar);

// these are the main draw methods, that all others use internally
pub fn draw(&mut self, item: &impl Drawable, color: Color, trans: Transform, z: impl Scalar);
pub fn draw_with_params(&mut self, item: &impl Drawable, params: DrawAttributes);
```
I hope I did not forget any combination. If so, it's probably something I'd never use so... yeah.

Also, I think draw_ex stands for draw exhaustive because it requires all parameters.

**Comment by ryanisaacg** [comment]
I agree these functions definitely need work! What can I say, it seemed fine at the time. I don't have time to discuss now, but I'll definitely write my thoughts down before tomorrow.

**Comment by Byter09** [comment]
I have no idea whether "Frame" is something, thats already taken by something else in terms of GPU stuff, but it sounds fitting right? A frame, like in the real world, can contain an image, has a position, and can also be transformed if need be.
My idea with the given methods above, is not bad then? I dont know.

Oh and offtopic but maybe important to you @ryanisaacg: I just started a project with a friend using Gitlab and oh my god its so much better than GitHub. I even build windows stuff using mingw64 (running tests is not possible but... I'm taking that risk as I'm also testing in linux). If you want to, I can open an issue regarding this.

**Comment by Xoronic** [comment]
Maybe an `ImageInstance`, a `Frame`, a `Wall`?

But wouldn't it make more sense to give the rectangle a `background` member? It could be an `Enum`: Something like

```rust
// Could be defined in the quicksilver API
enum Filling {
    Image(&quicksilver::Image),
    Color(quicksilver::Color)
}

struct Rectangle {
    pos: Vector,
    size: Vector,
    bg: Filling
}
```

And then the rectangle could be drawn with a filling: either an image or a plain colour.

**Comment by ryanisaacg** [comment]
This actually gives me the idea of texturing being a parameter to DrawAttributes, and not its own top-level Drawable. It wouldn't be too difficult to add an optional image parameter to add_vertices, and allow users to apply a texture to a set of untextured vertices and triangles. This would also mean that you can texture an arbitrary shape, rather than just being able to draw rectangular versions of images.

A possible draw call of an image with this system might look like:

`draw_image(&Rectangle::new_sized((32, 32)), &image);`

Does that sound like a good idea?

**Comment by Byter09** [comment]
Then there'd be even more `draw_*` methods but I guess thats.. fine?
If you implement that, how would one say which vertices takes which position on the image itself? Thats arbitrary right? Imagine having an image that contains lots of smaller images (like a collection of textures in a game), and you want your rectangle - or actually any shape, as you said - to only have the texture of a part of that image.

**Comment by ryanisaacg** [comment]
`Image` already has the ability to take a rectangular sub-image, so only having a part of the image is a mostly solved problem.

I would say that the furthest-left Vertex should be mapped to the left edge of the image region, the furthest-top Vertex to the top edge of the image region, etc.

**Comment by Byter09** [comment]
Which then does not allow having a huge image with multiple smaller images on it and selecting the area on it. But... if thats okay for now i'd say its fine? Never really worked with `Image` so I have no idea what its usecases are right now.

Why not get rid of `Image` completly and allow texturing any shape? Does that work?

**Comment by ryanisaacg** [comment]
It actually does allow for having a huge image and having multiple smaller images on it.

Basically, an `Image` is an abstraction that combines the texture handle from the GPU (currently OpenGL and WebGL) with a selected region (represented with a Rectangle.) So if you load an image from a file, it is loaded into an `Image` with a region that encompasses the entire area. If you use `Atlas`, it will use a manifest file to determine what regions should make to what names. You can also manually use `subimage` function to extract a piece of an `Image` into a new `Image` instance.

**Comment by Byter09** [comment]
Ah well. Then I guess `Image` has its place. Let's notify @Xoronic as this is not really a topic I have any knowledge of. :P

But here's the thing: This is something completly seperate from the actual reason this issue exists. So if you add a new method for image stuff, we can later open up a new issue and complain about it 😝 
No seriously, from what I understood, it sounds great.

**Comment by Xoronic** [comment]
> texturing being a parameter to DrawAttributes

Sounds good to me!

>  This is something completly seperate from the actual reason this issue exists. 

I agree. It should have a separate issue.

**Comment by Byter09** [comment]
Looks nice actually. I'd still keep the basic functions you mentioned first and implement the last one additionally (maybe in a separate PR?). This way the basics could use the "advanced" one internally or vice versa.

**Comment by ryanisaacg** [comment]
Here's a vague outline of my plan, to be executed over a number of PR's:

- Create a windowing module, which includes window, view, and resize
    - These are very barely `graphics` concepts, and are more about how the abstract graphics end up on the user's screen
    - The graphics module is getting crowded
- Create a Mesh struct, which holds a list of vertices and indices, and make the existing lists of vertices and indices in Window a mesh instance, which also means having Drawable take a Mesh instead of a Window (an advantage here is I basically am already doing something like that in the `lyon-integration` branch)
    - It would be nice to have some way to store drawn shapes as vertices and indices long-term, like rendering all the tiles in a level, without having to go through the overhead of switching in and out a frambuffer for a Surface
    - Additionally if a user wants to cache complex SVG graphics in any meaningful way, they need a Mesh-like data structure, so a general-purpose Mesh is probably a good idea
- Create a `Background` enum with `Color` and `Image` variants, and make Image no longer `impl Drawable` (this also means removing Color from `DrawAttributes`)
    - If there's always exactly one background, it's a mandatory parameter. Each draw call needs some shape to draw, and what to put behind it
    - This leaves only two other parameters, which aren't particularly wordy to include default verisons of. In fact, the builder pattern would probably always be more verbose
- This means we can simplify the draw API surface to just:

```rust
fn draw(&impl Drawable, &impl Into<Background>);
fn draw_ex(&impl Drawable, &impl Into<Background>, Transform, impl Scalar);
```

**Comment by Byter09** [comment]
Uh, absolutely love it. Would this also mean, that one could put whatever he/she wants onto a mesh, and save that instead of the raw shapes and redraw the mesh with whatever parameters necessary? Think of building any shape out of other shapes, some with texture, some without, then putting them on a mesh and only redraw that every draw call?

**Comment by ryanisaacg** [comment]
Yup! You would be able to render anything and everything into a Mesh, though if you change the contents of a Surface that you've drawn to a Mesh, it will draw with the *new* version rather than the *old* version. As long as that's documented, it shouldn't be a problem.

**Comment by ryanisaacg** [comment]
Yeah, I think you're right, I got a little too clever for my own good 😅 

My goal there was to allow:
```rust
window.draw(&Rectangle::new(5, 5, 32, 32), &Color::GREEN);
```
and
```rust
window.draw(&Rectangle::new(5, 5, 32, 32), &my_image);
```

But if you import the enum arms, actually just passing the enum isn't that bad, verbosity-wise:
```rust
window.draw(&Rectangle::new(5, 5, 32, 32), Colored(Color::GREEN));
```
and
```rust
window.draw(&Rectangle::new(5, 5, 32, 32), Textured(&my_image));
```

so I I think I'll go with your signatures.

**Comment by ryanisaacg** [comment]
This seems resolved to me: there are now only two draw functions, and the distinction seems pretty clear. Let me know if I should re-open this, though.

**Comment by Xoronic** [comment]
I really like what you did in the latest changes! I still think we should consider renaming `draw_ex` though.. Or at least document what it means :)

**Comment by ryanisaacg** [comment]
I can't believe I forgot to do that! I totally intended to document it.
