### ISSUE TITLE
Vector drawable?

### ISSUE THREAD

**Issue by Xoronic** [ryanisaacg/quicksilver#316]
## Why is a `Vector` drawable?

Line 330 in src/vector  (development-branch):
```rust
impl Drawable for Vector {
    fn draw(&self, window: &mut Window, params: DrawAttributes) {
        Rectangle::new(*self, Vector::ONE).draw(window, params);
    }
}
```

So `Vector::draw` draws a rectangle at the position of the `Vector`? Why? Should `vector.rs` actually be located in `src/geom/objects` then?

1. It does not make sense
2. I cannot think of any practical usages of it

*( I'm on an API-consistency warpath :P )*

EDIT: So my suggestion is obviously removing the implementation. (But I might have overseen something important)

**Comment by Byter09** [comment]
It makes sense when I want to paint a specific pixel...?
I could simply draw a Vector instead of a Rectangle with 1x1 size.

My opinion on this is: It works, requires basically no support (there's nothing really there that could break) and the user _can_ but does not have to use it.

Also, please note, that the objects folder was my idea for upcoming more complex shapes, which are now on halt because of lyon. I was about to propose moving rectangle, circle and vector in there, but was not quite sure how that would be received.

**Comment by Byter09** [comment]
Though, I think it is now possible to optimize the drawing. Because we now have access to vertices, we could instead draw a simple triangle instead of two (because of the rectangle having two).

**Comment by Xoronic** [comment]
Hmm, in my opininion, a `Vector` is like a metric, something like a `Scalar`. The only difference between a `Vector` and a `Scalar` is the extra dimension.. It is not a shape, as it does not have a size. We don't want to draw `Scalar`s either, right?

**Comment by Xoronic** [comment]
IMHO, It is a datastructure for a position, and it should be nothing more than that

**Comment by Byter09** [comment]
Theoretically, yes. But pixels are rectangles themself, so that only makes sense.
And I imagine drawing a miniature circle instead of, as I said above, a single  triangle is way more complicated than it has to be.

So if you really want to do something about this, how about copying Vector again, create a new Point object and instead of it drawing a rectangle, make it draw a tiny triangle. You do not even have to use the triangle object. The code from the RGB triangle example is exactly what you'd need.

**Comment by Xoronic** [comment]
In what case would you want to draw a single pixel then?

**Comment by Byter09** [comment]
Which is a `GpuTriangle` with its vertices all on the same position.

**Comment by Xoronic** [comment]
I think that it isn't a good idea to let API consumers draw individual pixels using tiny rectangles. That is very inefficient.

**Comment by Xoronic** [comment]
It sounds like something where using an `Image` (In essence a structure with a lot of pixels) or an `Animation` if the pixels should change over time is appropiate.

**Comment by Byter09** [comment]
Which is why I said, that at least the drawing method could be changed to draw a tiny triangle instead. This way you get rid of the two triangles of the rectangle and still allow for end-users to have the feature of drawing single pixels. If a end-users would have to implement drawing pixels themself, some would probably go the "tiny-Rectangle" route, or worse "tiny-Circle". So better to have it in quicksilver itself in the most efficient way.

**Comment by Xoronic** [comment]
> Which is why I said, that at least the drawing method could be changed to draw a tiny triangle instead. This way you get rid of the two triangles of the rectangle and still allow for end-users to have the feature of drawing single pixels. If a end-users would have to implement drawing pixels themself, some would probably go the "tiny-Rectangle" route, or worse "tiny-Circle". So better to have it in quicksilver itself in the most efficient way.

But it is not efficient. Drawing tiny rectangles would require 3 `Vector`s and 1 colour value, where drawing an `Image` only requires sending 1 colour value to the GPU.

If API-consumers want to draw multiple pixels, they should create an `Image` and render that.

**Comment by Xoronic** [comment]
API-consumers can create an `Image` using `Image::from_raw` where they can provide an array of colour-values.

**Comment by Byter09** [comment]
No you probably misunderstood. I'm saying, that first of all the current implementation of drawing a vector is bad. Currently its using a rectangle, which internally draws two triangles with 4 vertices. Instead this should be changed to three vertices and a single triangle, all on the same position. Same result, more efficient way.

Secondly, this is not about whether drawing single pixels is good or not. The point being having the option is better than having no option at all.

And last but not least, an Image still draws a Rectangle internally. If, however you're suggesting some way to draw multiple pixels at once, then yes, maybe an Image is a good choice for that, but this is about drawing a single pixel, not multiple.

If this doesn't clear it up, I probably do not fully understand what exactly you're saying :P

**Comment by Xoronic** [comment]
> having the option is better than having no option at all

I think that having the option is **worse** than having no option at all in this case. If there is a function for it, API-consumers will assume that it is fine to use it. 

They **will** eventually abuse it and draw images using "individual pixels", which should be strongly discouraged.

And, if a (very rare) API consumer is *really* persistent and wants to draw one single pixel using triangles (which should not be done), they *can* do it anyway, by using `Triangle`s.

- Someone drawing a single pixel seems very, very rare
- Doing so is still possible (just harder) if the function is removed
- Drawing a `Vector` makes no sense mathematically
- Drawing multiple pixels using triangles is extremely inefficient (and people will eventually abuse it for this purpose, especially if this project gains some popularity)
- There is a great alternative for drawing individual pixels: an `Image`

**Comment by Byter09** [comment]
Now this is some reasoning I can get behind. Yeah you basically invalidated all my points. :'(

Oh and that one point mentioning that drawing Vectors is nonsense? I at least agreed on that from the start :P

Just create a PR and see where it goes?

**Comment by Xoronic** [comment]
Sure, let's see! Thanks by the way for testing my arguments, I could have completely misunderstood the situation :)

I do not have the time right now to create a PR so either you could do it or I will do it later today :)

**Comment by ryanisaacg** [comment]
Just as a quick FYI- I think being able to draw a single point of color is valuable (I've personally used it for things like simple particle systems.) Also, `Vector` would become the only thing with a position that cannot be drawn if the `Drawable` impl were removed.

I appreciate the thought you've put into the performance characteristics, but unfortunately you've drawn a few incorrect conclusions. Drawing an image is more expensive than drawing a rectangle. I actually can't think of a scenario in Quicksilver where this isn't true. Drawing images requires switching the active image on the GPU, and to sample the RGBA value from the texture, whereas shape rendering doesn't.

Additionally, I don't think we should be worried about a user trying to draw an image pixel-by-pixel. It's an edge case I struggle to think would ever happen; anyone who has enough programming smarts to acquire the RGB values for every pixel in their image can probably check the examples or documentation to look at `Image.`

Again, thanks for all the passion and interest you've shown in Quicksilver, but currently I would not merge a PR to remove `Drawable` from Vector.

**Comment by Byter09** [comment]
I guess my points were not so invalid after all. Now, there's still one things that _can_ be fixed:
Use a triangle instead of a rectangle when drawing the vector. This decreases vertices and triangle count not by much, but it's at least a bit more efficient :D

**Comment by Xoronic** [comment]
I think that my idea is not that weird and I'm a bit surprised by you closing the issue and the unfounded statement that I "unfortunately have drawn a few conclusions incorrect" without having seen any benchmark or test.

> Also, Vector would become the only thing with a position that cannot be drawn if the Drawable impl were removed.

A scalar is not drawable either. `Vector`s and `Scalar`s are different from shapes, as they do not have a width, height or radius. I find that enough of a reason to leave it out of the API, actually.

> unfortunately you've drawn a few incorrect conclusions.  Drawing an image is more expensive than drawing a rectangle. I actually can't think of a scenario in Quicksilver where this isn't true. 

Drawing a *single* image is more expensive than drawing a *single* rectangle. But I expect (We could test it) that drawing a bunch of them to form an image is not. 

Also, the option to draw a pixel would not be fully removed from the API, it would be still possible to create a rectangle of size (1,1).

**Comment by Byter09** [comment]
As much as I support @ryanisaacg most of the time, I have to agree with you here @Xoronic.

Can I maybe interest you both in a compromise?
Let just say, that Vectors are simply a mathematical utility. This invalidates them as something graphical, as @Xoronic pointed out. The graphical analogy would be a Point, which again is actually not drawable because it is infinitesimally small, but because we're drawing to pixels here, one could draw a point.
If we now say, that this point is drawable, we could at the same time optimize the drawing itself by using a single triangle. (See RGB triangle example, not the Triangle object)

This shifts the important part to a valid object and makes vectors a utility for calculation. Both parties get what they want and we also slowly move all drawables in the objects directory... :)

**Comment by Xoronic** [comment]
I like that idea. I think it is the best idea so far, actually. 

The example of a particle system is a good argument I did not think of to support drawing individual pixels on the screen, but I don't like the `Vector` being drawable. What @Byter09 proposes seems to be the best solution.

@ryanisaacg what do you think?

**Comment by ryanisaacg** [comment]
I mean, everything that's a shape is a mathematical concept 😛 

To be honest, I don't feel like there needs to be a separate Point type. Not every pixel on the edge of a drawn circle is equi-distant from the center, even though a mathematical circle is; the Vector is not drawn infinitely small, even though it should be. Lines aren't drawn with infinite thin-ness either.

I also don't like trying to optimize it by reducing it to 1 triangle, because that will work on an un-scaled application but look questionable when scaled up, because it will be a triangle instead of a square pixel.

There *are* ways to draw a Vector without that impl, but I don't really buy that argument as being grounds for removal. There are a lot of quicksilver features that are just composing other features; Line is a transformed rectangle, and users can implement new shapes themselves through `add_vertices`.

**Comment by ryanisaacg** [comment]
That said, I would be open to a type alias called Point that maps to Vector, I suppose?

**Comment by Byter09** [comment]
That is _exactly_ what I had before pushing Line/Triangle. Weird.

Seriously, the content of `point.rs` was
```rust
pub type Point = Vector;
```

I guess my first instinct at that time was right. I also used Point wherever possible when describing Line and Triangle because that's what it is. Vector felt wrong somehow :D
