### ISSUE TITLE
Does it support to make canvas/webgl paint app?

### ISSUE THREAD

**Issue by nvcken** [ryanisaacg/quicksilver#327]
Would you please tell a sample for it

**Comment by ryanisaacg** [comment]
I'm not entirely sure what you're asking; do you want to know if Quicksilver supports canvas and webgl in general? Or are you more specifically asking about something like MS Paint that allows the user to draw?

**Comment by nvcken** [comment]
Actually both of them
1. Does Quicksilver support webgl and fallback canvas API if webgl is n/a
2. Is if possible web paint app with quicksilver

**Comment by ryanisaacg** [comment]
Quicksilver supports WebGL, but doesn't currently have a canvas fallback (largely this is because WASM support and WebGL support are pretty comparable, but if a reasonably performant canvas backend were to be added as a PR I would be open to merging it.)

Currently there's no way in Quicksilver to save a file to the user's hard drive; on desktop, the std library suffices, but on WASM it would require interacting with Web API's. There are definitely use cases for this in this issue and others, so it will probably be added at some point. If you don't care about saving the web paint creations to the actual machine, then I suppose Quicksilver can be useful.

**Comment by nvcken** [comment]
Would you pls tell anyway to benchmark or determine render performance likes fps to compare WASM vs without WASM enable ?

**Comment by ryanisaacg** [comment]
I'm sorry, this totally slipped past me!

I'm not sure what you mean with WASM enabled vs WASM disabled; do you mean running outside vs inside the browser? If so, there's a new `average_fps()` function in the development branch that you could try out.

**Comment by ryanisaacg** [comment]
I'm going to close this for now, let me know if you have any other questions!
