### ISSUE TITLE
Image::load(...).wait()? causes "unreachable executed" with WASM

### ISSUE THREAD

**Issue by beatgammit** [ryanisaacg/quicksilver#354]
**Describe the bug**
If I modify the image example to use `Image::load("image.png").wait()?`, I get an error when loading the example.

**To Reproduce**
1. Load asset synchronously using `Future::wait()`
2. See error message

**Environment and versions (please complete the following information):**
- Environment: Arch Linux, Firefox
- Rust compiler version: Rust nightly 1.30 (2018-08-05)
- Quicksilver verison: latest development branch

I think we could solve this through documentation/tutorial, but it would be nice if it worked.

**Comment by beatgammit** [comment]
A really annoying side-effect here is that I can't figure out a nice way of handling multiple assets. If assets were `Copy`, perhaps I could do something like this:

    self.asset = Asset::new(...);
    {self.asset}.execute(|asset| self.myAsset = Some(asset));

My primary use case here is to load a file (e.g. a level) that contains information about how to render the scene. I'm not sure how I can get around this without either synchronous file loading or `Copy`-able `Asset`.

If this is currently possible, it would be awesome to have an example of doing it. Basically, I want to render an `Asset` depending on the content of another `Asset`.

**Comment by ryanisaacg** [comment]
`Futures:wait` unfortunately isn't going to be available on WASM, because of the limitations of the platform (If you don't yield control of execution back to the browser, the UI will freeze, loading will not progress, etc.) 

However, you're right in that the combinators is the solution. The Futures API allows things like:

```rust
join_all(
    vec![Image::load("image1.png"), Image::load("imagep2.png")])
),join(
    join_all(
        vec![Sound::load("sound1.ogg"), Sound::load("sound2.ogg")])
))
```

which will creates a Future that will yield `(Vec<Image>, Vec<Sound>)` when loaded.

The Font example can give you an example of a future that needs to transform the loaded data as part of loading it (probably what you'll want to do with loading your level.)

I would recommend looking into docs on the `combinator` module (which is just a re-export of the [future module in the futures crate](https://docs.rs/futures/0.1.21/futures/future/index.html)) to get an understand on how to combine futures together.

**Comment by beatgammit** [comment]
I might throw together an example that loads two assets and renders them, as well as include something in the docs somewhere about `.wait()` being problematic.

I think the proper solution here is statically compiling in assets, which would resolve most of my problems.

**Comment by ryanisaacg** [comment]
This is now documented in the tutorial (and also will only be a problem until async / await).
