### ISSUE TITLE
Attempting to use immi functionality but only seeing a blank screen

### ISSUE THREAD

**Issue by tyler-conrad** [ryanisaacg/quicksilver#415]
I'm attempting to use the immi GUI functionality provided by quicksilver but am unable to get a minimal example working.  Basically I'm trying to initialize the immi context and draw an image but all I'm getting is a blank screen.

The minimal example I'm trying to get working is here: https://github.com/tyler-conrad/immi_test  Any pointers on what I may be missing would be appreciated.

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

rustc 1.30.1 (1433507eb 2018-11-07)
binary: rustc
commit-hash: 1433507eba7d1a114e4c6f27ae0e1a74f60f20de
commit-date: 2018-11-07
host: x86_64-unknown-linux-gnu
release: 1.30.1
LLVM version: 8.0

quicksilver = "0.3.2"
immi = "1.0.4"

**Comment by Xoronic** [comment]
I compiled it as well. I can confirm that only a blank screen is shown.

I'm not sure if it is a bug or expected behaviour. I have never used immi with quicksilver, so I can't tell if this is the way to do it *(adding an example for it?)*

### Stats

| Item                            | Value                    |
|---------------------------------|--------------------------|
| OS Name                         | Microsoft Windows 10 Pro |
| Version                         | 10.0.17134 Build 17134   |
| System Type                     | x64-based PC             |
| Installed Physical Memory (RAM) | 12,0 GB                  |

I am using **rustc 1.31.0 (abe02cefd 2018-12-04)**

### By the way, the mouse position
I have spotted one error in your code, *but after fixing it, the blank screen was still shown*.

The immi documentation says: 

```rust
/// The cursor coordinates, if any, must be in OpenGL viewport coordinates. In other words,
/// `[-1.0, -1.0]` corresponds to the bottom-left hand corner of the screen, and `[1.0, 1.0]`
/// to the top-right hand corner.
````

Quicksilver does not give you OpenGL viewport coordinates. I adjusted your code a bit to convert the coordinates (main.rs#L53)

```rust
self.assets.execute(|(font, image)| {
    let mut ui_renderer = ImmiRender::new(window.mesh(), font);

    // Scaled from -1 to 1. (-1 being the left of the window, 1 being the right of the window)
    let mouse_x_normalized = (mouse_pos.x / window_size.x) * 2f32 - 1f32;
    // Scaled from -1 to 1. (-1 being the bottom of the window, 1 being the top of the window)
    let mouse_y_normalized = (mouse_pos.y / window_size.y) * -2f32 + 1f32;

    println!("{}, {}", mouse_x_normalized, mouse_y_normalized);

    let ui_context = immi::draw().draw(
        window_size.x,
        window_size.y,
        &mut ui_renderer,
        Some([mouse_x_normalized, mouse_y_normalized]),
        mouse_left_pressed,
        mouse_left_released,
    );
    ImmiTest::draw_ui(&ui_context, &ui_state, image)?;
    Ok(())
})?;
```

**Comment by ryanisaacg** [comment]
I have also reproduced the issue, I hope to have a fix soon.

**Comment by ryanisaacg** [comment]
I've figured out the issue: when immi is rendered, the vertices are not projected into the Window space correctly. It will require a slight API change, and I'll be adding a convenience method to create UI contexts using a Window.

**Comment by ryanisaacg** [comment]
Should be fixed on the development branch, and it will be in the next release (in the next week or so).
