### ISSUE TITLE
How to wait on asset loading 

### ISSUE THREAD

**Issue by codec-abc** [ryanisaacg/quicksilver#452]
Hi, 

This is certainly a newbie question. I managed to load and use assets (images and sound). But I noticed that since asset loading is not blocking sometimes I can only hear sounds after they are loaded and miss the few times they should be play. So, I want to block on asset loading.

Today I have something like this:
```rs
sounds.push(Asset::new(Sound::load("chat.wav")));
```

I would like something like this 
```rs
sounds.push(Asset::new(Sound::load("chat.wav").wait()));
```
but this doesn't compile, and I tried different thing but got no luck and started to fight the compiler. Would you be kind enough to show a very basic example of blocking resource loading please?

**Comment by ryanisaacg** [comment]
Currently there isn't any way to blocking load, because if you block in WASM you will hang up the user's browser. When async / await syntax is stabilized for Rust, then the API can present a blocking-like interface.

If you want to include the asset in the executable itself, you can use [`include_bytes`](https://doc.rust-lang.org/std/macro.include_bytes.html) and `Image::from_bytes`. This means there will be no loading period. However, this is currently not supported for Sounds (see #330).

**Comment by codec-abc** [comment]
Ok, thanks for the feedback, I will leave the issue open so we can track it for when async / await lands. Also, while if isn't possible to block on asset loading, is it possible to know if the asset is loaded? That way I can show a loading screen and do some polling in each update to see if all the needed asset are done loading.

**Comment by ryanisaacg** [comment]
The way Assets are intended to be used are through the `execute` methods, so if you want to run some code if an Asset is done and some other code if it's not, you would use [`execute_or`](https://docs.rs/quicksilver/0.3.5/quicksilver/lifecycle/struct.Asset.html)

**Comment by ryanisaacg** [comment]
With the new alpha release, you can conveniently use `.await`!

**Comment by codec-abc** [comment]
Thanks. Will definitively test it!
