### ISSUE TITLE
Immi label not working correctly

### ISSUE THREAD

**Issue by rsribeiro** [ryanisaacg/quicksilver#456]
**Describe the bug**

I've been trying to use the "Label" from the Immi dependency, but it's not working. Maybe I'm doing something wrong. The label appears to be rendered wrongly, or doesn't appear on the window at all.

**To Reproduce**

I've modified the immi example to render a label instead of a button:

Inside self.assets.execute:
```
use immi::{
    Alignment,
    HorizontalAlignment,
    widgets::{Interaction, image_button, label}
};
...

let ui_context = create_immi_ctx(ui_status, &mut ui_render)
    .rescale(0.25, 0.25, &Alignment::center());

let style = FontStyle::new(48.0, Color::BLACK);
// label::flow(&ui_context, &style, "HelloWorld", &HorizontalAlignment::Center);
label::contain(&ui_context, &style, "HelloWorld", &Alignment::center());
```

**Environment and versions (please complete the following information):**
- Environment: Windows 10 x64 (desktop and wasm)
- Rust compiler version: stable
- Quicksilver verison: 0.3.6

**Comment by ryanisaacg** [comment]
I will look into this and hopefully get back to you by this weekend.

**Comment by ryanisaacg** [comment]
Ok, so I looked into it: the problem was that Quicksilver wasn't passing the glyph images correctly in its immi implementation. I've fixed that, but there are still some issues with the immi font rendering (namely that it looks bad) so I'm going to see if I can get those fixed as well. For now, my WIP is on the branch `immi-font-fixes` if you want to use that version until it's merged.
