### ISSUE TITLE
Anti-Aliasing in webgl

### ISSUE THREAD

**Issue by codec-abc** [ryanisaacg/quicksilver#476]
Hi,

I am a little bit confused about WebGL MSAA supports. I found several articles [like this one](http://www.realtimerendering.com/blog/webgl-2-new-features/) or [this one](https://stackoverflow.com/questions/28220260/change-the-number-of-msaa-smaples/28229394#28229394), but the message from [this commit](https://github.com/ryanisaacg/quicksilver/pull/361/commits/8b7dbc77472b561d55576fa990f803abe1c28e12) suggets that WebGL doesn't support MSAA.

So, what the option to get MSAA (or any AA) for WebGL?

By the way, I am asking the question because I compiled my game for desktop and web and with AA on desktop it is way more pretty.

**Comment by ryanisaacg** [comment]
WASM doesn't support MSAA except when rendering to a framebuffer. Quicksilver's Surfaces don't support MSAA, but if they did you could render your whole scene to a Surface with MSAA enabled, and then render that to the screen.

If you'd like to look into a pull request to add MSAA to Surfaces, feel free. Otherwise I will get to it eventually, but I can't promise it will be soon.

**Comment by codec-abc** [comment]
Thanks for the answer

> If you'd like to look into a pull request to add MSAA to Surfaces, feel free. Otherwise I will get to it eventually, but I can't promise it will be soon.

I don't feel I master enough Rust and graphics API to make a decent pull request. Also, I suspect adding MSAA is a bit tricker than just telling the underlying API to use it, otherwise Quicksilver's Surfaces would already support it. So I rather wait for support and then use a surface to do the rendering.
