### ISSUE TITLE
Add the ability to end an animation

### ISSUE THREAD

**Issue by seanvoss** [ryanisaacg/quicksilver#496]
**In the graphics package, animation class all the data necessary to determine if I have completed an animation is scoped to private**

**Describe the solution you'd like**
Allow the calling program to know whether an animation has ended and will be looping via exposing a method to ask this question, or providing public scope to the data frames.

**Are you interested in contributing?**

I can make the patch once we have a go forward plan.

**Comment by ryanisaacg** [comment]
It seems to me that the Animation abstraction in general is quite bad, but this should be relatively easy to fix: adding a length and an index method.

However, I will probably be deprecating Animation soon, because it probably would be better for users to create their own or to pull in a more featured animation library.

My recommendation is to just create your own Animation that is tailored to your specific needs.

**Comment by ryanisaacg** [comment]
Animation has been deprecated in the most recent release, because a custom solution will probably be best in all cases.
