### ISSUE TITLE
Made with quicksilver- Slavic castles

### ISSUE THREAD

**Issue by Leinnan** [ryanisaacg/quicksilver#543]
I am making game using quicksilver, you can add it to readme if you want.
Link to repo: https://github.com/Leinnan/slavic_castles
Game live: http://leinnan.ayz.pl/ukw/slavic_castles/index.html
Itch.io: https://leinnan.itch.io/slavic-castles

I've also noticed that on desktop memory usage of my game stays around 70MB, but on web it grows to very big values, do you notice same in own projects or I do something wrong regarding quicksilver?

**Comment by ryanisaacg** [comment]
Thanks, I've added you to the readme!

Regarding the memory usage, I'm not sure. It could be a memory leak of some kind in the binding; what size memory values are you observing?

**Comment by Leinnan** [comment]
I've tried I little and the grow is so big if you leave game open for half hour it will make Firefox crash :/

**Comment by ryanisaacg** [comment]
Ok, I'll look into this at some point, and also I'll try to see if I can replicate it with the upcoming `quicksilver-next` branch.

**Comment by lenscas** [comment]
For what it is worth, my game doesn't seem to have this problem. ( https://lenscas.github.io/arena_keeper_quick/ ). However, I also don't do anything particularly fancy. 

Edit: I quickly looked at slavic castles. It seems that this problem is worse during the actual game then on the main menu. In fact, on the main menu it happens so slowly that I didn't notice it at first. 

I also used the devtools to take 2 snapshots of the memory, and it seems that something labeled as "Webgl texture" is what is increasing. When I make 2 memory snapshots of my game however "Webgl texture" isn't even listed as something that changed.

**Comment by Leinnan** [comment]
Maybe I am doing something wrong when I draw. For example: https://github.com/Leinnan/slavic_castles/blob/master/src/ui/card_displayer.rs It is my first project in Rust so there is still option that I am doing something that I should not.

**Comment by lenscas** [comment]
Something that you do different than me is that you turn the text into an image every frame, rather than just once.

**Comment by lenscas** [comment]
I cloned Slavic castle and changed button.rs to only render the text to an image once. This seemed to have stopped the memory leak on the main menu, or made it occur so little that it is pretty much no problem.

**Comment by ryanisaacg** [comment]
This seems all resolved, feel free to re-open if not.
