### ISSUE TITLE
Please remove requirement of `static` directory

### ISSUE THREAD

**Issue by woodywood117** [ryanisaacg/quicksilver#586]
Forcing the user to have a static directory from wherever they're running the program is not a great design decision. It feels like forced rigidity. I'm sure you had a reason for putting it in there, I just don't understand why. Could you either remove this or add the functionality to override it?

**Comment by lenscas** [comment]
the static directory is something that comes from std-web/cargo-web, and is used so running `cargo web start` knows which files are static and thus should be accessible through the web server.

Having said that, not having one only gives an warning doesn't it (it also prevents you from loading files the normal way for the reason stated above.)?

I also just took a quick look at `platter` (the library used for loading files in quicksilver 4), it seems to just take a path for the desktop, so I think the static folder already isn't a thing in both end results

With that I mean that if you have a folder structure like
```
/static/awesomeGameData/someFile.png
```
The user simply gets the compiled binary along with a folder called `awesomeGameData` containing `someFile.png` and on the web it will make a request to `/awesomeGameData/someFile.png` in order to get `someFile.png`

**Comment by ryanisaacg** [comment]
In the new alpha versions, wasm-bindgen is now an option for development (which would bypass the cargo-web requirements.) I'm not sure it makes sense to keep locking users into `static/` at this point, but I don't know if there's an alternative for `cargo-web` users. Possibly reviving https://github.com/koute/cargo-web/pull/158 to allow custom directories?

**Comment by johnpmayer** [comment]
I'm curious, is there any finger-in-the-wind prediction whether either of the Rust web tool chains, between cargo-web and wasm-bindgen/wasm-pack, is going to "win" long-term? I've used both with quicksilver and don't have a strong preference nor have I bench-marked anything.

**Comment by lenscas** [comment]
I read that Yew is planning to switch from std-web to wasm bindgen. However they currently support both because they think that std-web + cargo web is easier to setup/use than wasm-bindgen. (I have never used wasm-bindgen so no idea if that is true)

**Comment by ryanisaacg** [comment]
Cargo web and stdweb are still much easier to use and set up, but they face the downside of being a single-person project and not having all the web APIs already bound to. web-sys is a successful project that has generated Rust interfaces for all of the web platform, whereas stdweb relies on manually writing idiomatic bindings.

Once wasm-pack and related workflow projects improve, I think web-sys is a better bet in the long run.
