### ISSUE TITLE
How to render a quicksilver::geom::Line with certain color?

### ISSUE THREAD

**Issue by bluretrece** [ryanisaacg/quicksilver#597]
Hello, 

I'm trying to use quicksilver for plotting a few points, as simulating lines in a cartesian plane, but unfortunately I'm not able to see any method that allows me to display or render the lines I'm creating. 
`Graphics::stroke_path` creates straight lines too, but I'm not able to change its color or thickness. Any idea of how can I solve this? I would appreciate any suggestion. Thanks in advance!

**Comment by ryanisaacg** [comment]
This probably isn't the answer you want, but I didn't realize `Line` had made it into the alpha. I will probably remove it before the next release, because it's misleading.

If you want to do line rendering, many modern systems will actually fail to set the thickness of lines. The line rendering method is just for rendering 1-pixel-thick lines; you can use transformations on other shapes to create thick lines, or look into something like [lyon](https://docs.rs/lyon/0.15.6/lyon/) for turning a shape into a series of draw-able triangles. Lyon integration will be arriving in the alpha at some point, hopefully soon.

**Comment by ryanisaacg** [comment]
Given that Line has been removed in the latest release, I'm going to close this.
