### ISSUE TITLE
Add an animation system?

### ISSUE THREAD

**Issue by lenscas** [ryanisaacg/quicksilver#611]
**Describe the problem you want to solve**
I didn't see anything about an animation system on the 0.4 issue, despite the fact that quicksilver 0.3 had a (deprecated) one.

**Describe the solution you'd like**
I happen to have made a new animation system that I was planning to use and release as its own library. However, before I do that I wanted to know if this wasn't something that could be part of quicksilver instead. The code can be found at https://github.com/lenscas/silver_animation

It isn't anything too fancy, but at the very least it should be a good starting point?

**Are you interested in contributing?**
yes, I am willing to make a pull request for it myself.

Anyway, feel free to say no if you don't like the idea.

**Comment by ryanisaacg** [comment]
I think I'm going to say animation is out-of-scope. Primarily, this is because there are so many different things you may want to do with an animation library. At the simple level, you could do something like Quicksilver 0.3 had: a simple looping list of images. At a complex level, you have something more akin to a scripting layer (behaviors, sounds, or other things dependent on the progress of a given animation.)

Also, it can easily live as an external crate. I really like the look of silver_animation!

**Comment by lenscas** [comment]
Then I will release it as its own library. Expect a pull-request soon to add it to the library list :)
